### ISSUE TITLE
Consider integrating with 0data protocols

### ISSUE THREAD

**Issue by rosano** [anita-app/anita#1]
In addition to local storage, people can connect their personal data stores https://hello.0data.app

**Comment by ilDon** [comment]
Hi Rosano, thanks for mentioning 0data protocols, this is definitely the direction I have in mind for Anita. At one point data sync between devices is a must, and decentralized solutions are those that interest me the most. As I have multiple commitments now I fear it would take me a while, I'd be happy though to add contributors to the project if you want to add you inputs :-)

**Comment by ilDon** [comment]
Priority now is on other strategies to offer sync between devices. Any contribution to support the protocols mentioned in [0data.app](https://0data.app/) are welcome.
